const actionTypes = Object.freeze({
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    FETCH_DENDER_START: 'FETCH_DENDER_START',
    FETCH_DENDER_FAILDED: 'FETCH_DENDER_FAILDED',
    FETCH_DENDER_SUCCESS: 'FETCH_DENDER_SUCCESS',

    FETCH_POSITION_FAILDED: 'FETCH_POSITION_FAILDED',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',

    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

    FETCH_TOP_DOCTORS_FAILDED: 'FETCH_TOP_DOCTORS_FAILDED',
    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',

    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAILDED',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',

    FETCH_ALL_DOCTORS_FAILDED: 'FETCH_ALL_DOCTORS_FAILDED',
    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',

    CREATE_DOCTOR_INFOR_SUCCESS: 'CREATE_DOCTOR_INFOR_SUCCESS',
    CREATE_DOCTOR_INFOR_FAILDED: 'CREATE_DOCTOR_INFOR_FAILDED',

    FETCH_ALLCODE_SCHEDULE_TIME_FAILDED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILDED',
    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',

    FETCH_REQUIRED_DOCTOR_INFOR_FAILDED: 'FETCH_REQUIRED_DOCTOR_INFOR_FAILDED',
    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',


})

export default actionTypes;